### ISSUE TITLE
Not enough monads

### ISSUE THREAD

**Issue by tgvashworth** [passy/giflib-api#1]
I think there should be more monads, just in case.

**Comment by tgvashworth** [comment]
:+1:

**Comment by tgvashworth** [comment]
+1

**Comment by tgvashworth** [comment]
I agree, +1 to this _pleeeeeease add_.

**Comment by tgvashworth** [comment]
You'r lack of response here is telling. Merge or I'll tell all my friends in the io js community

**Comment by passy** [comment]
LIES LIES LIES, there are monads EVERYWHERE

**Comment by passy** [comment]
![](http://media.giphy.com/media/4u31bWDYmhw5O/giphy.gif)

**Comment by passy** [comment]
LOOK AT THAT FILTHY LIAR
![img_20150302_094348](https://cloud.githubusercontent.com/assets/9906/6438439/dc80627e-c0c0-11e4-9347-c77dc0aa9969.jpg)

**Comment by tgvashworth** [comment]
Creeeeeeepy.

(Dat booty tho.)
